### ISSUE TITLE
Make `--debug.etherscan` work for OP-Reth

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#10377]
### Describe the feature

Currently, it only works for Ethereum mainnet and testnets, we can make it work with Optimism and Base with their respective block explorers.

The reason why it doesn't work with OP-Reth is because we don't propagate the feature `optimism` as needed, so it crashes on an unknown transaction type:
```console
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.684561Z  INFO Using etherscan as consensus client
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.687001Z  INFO Starting consensus engine
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: thread 'tokio-runtime-worker' panicked at crates/consensus/debug-client/src/client.rs:212:66:
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: called `Result::unwrap()` on an `Err` value: Eip2718Error(UnexpectedType(126))
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: stack backtrace:
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.884896Z ERROR Critical task `etherscan consensus client` panicked: `called `Result::unwrap()` on an `Err` value: Eip2718Error(UnexpectedType(126))`
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.884993Z ERROR shutting down due to error
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: Error: Critical task `etherscan consensus client` panicked: `called `Result::unwrap()` on an `Err` value: Eip2718Error(UnexpectedType(126))`
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: Location:
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]:     /home/ubuntu/reth/crates/cli/runner/src/lib.rs:161:32
Sep 23 15:54:51 reth1 systemd[1]: op-reth.mainnet.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by royvardhan** [comment]
@mattsse Please assign this to me. Thanks!

**Comment by royvardhan** [comment]
According to the api documentation of both Base and OP, the query for getting the blocks is exactly the same which we are using right now in [EthereumBlockProvider](https://github.com/paradigmxyz/reth/blob/019ec727a2e078fd1517d5b04f39f6713d3bf0d7/crates/consensus/debug-client/src/providers/etherscan.rs#L38)

The next main concern is the `base_url` on which the query is run with the api token, it is also being provided in the args here, https://github.com/paradigmxyz/reth/blob/019ec727a2e078fd1517d5b04f39f6713d3bf0d7/crates/node/builder/src/launch/mod.rs#L381 if not supplied, it is automatically getting the `base_url` for both OP and Base from here https://github.com/paradigmxyz/reth/blob/019ec727a2e078fd1517d5b04f39f6713d3bf0d7/crates/node/builder/src/launch/mod.rs#L388 and then running the relevant code. 

What am I missing? 

CC: @mattsse

**Comment by shekhirin** [comment]
Oh, it may actually be already supported, you're right! We just need to test `--debug.etherscan` with OP-Reth running Optimism mainnet, testnet and Base mainnet, testnet.

**Comment by royvardhan** [comment]
> Oh, it may actually be already supported, you're right! We just need to test `--debug.etherscan` with OP-Reth running Optimism mainnet, testnet and Base mainnet, testnet.

All good, let me know if you need anything done from my side.

**Comment by emhane** [comment]
got this error trying to run `op-reth` with op mainnet etherscan api key

```
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.684561Z  INFO Using etherscan as consensus client
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.687001Z  INFO Starting consensus engine
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: thread 'tokio-runtime-worker' panicked at crates/consensus/debug-client/src/client.rs:212:66:
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: called `Result::unwrap()` on an `Err` value: Eip2718Error(UnexpectedType(126))
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: stack backtrace:
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.884896Z ERROR Critical task `etherscan consensus client` panicked: `called `Result::unwrap()` on an `Err` value: Eip2718Error(UnexpectedType(126))`
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: 2024-09-23T15:54:51.884993Z ERROR shutting down due to error
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: Error: Critical task `etherscan consensus client` panicked: `called `Result::unwrap()` on an `Err` value: Eip2718Error(UnexpectedType(126))`
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]: Location:
Sep 23 15:54:51 reth1 op-reth-mainnet[1224562]:     /home/ubuntu/reth/crates/cli/runner/src/lib.rs:161:32
Sep 23 15:54:51 reth1 systemd[1]: op-reth.mainnet.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by greged93** [comment]
hey @shekhirin can I work on this?

**Comment by mattsse** [comment]
we can close this now because we have this now generic over the block type
