### ISSUE TITLE
Reth fails to compile when I'm using it in an exex application 

### ISSUE THREAD

**Issue by Nesopie** [paradigmxyz/reth#10670]
### Describe the bug

Compilation stops when I'm importing reth in my service. Error seems to stem in the `reth-mdbx-sys`.

### Steps to reproduce

I'm following the [minimal example](https://github.com/paradigmxyz/reth-exex-examples/tree/main/minimal) in the reth-exex-examples repo and compiling it.

### Node logs

```text
error: failed to run custom build command for `reth-mdbx-sys v1.0.6 (https://github.com/paradigmxyz/reth.git#80793cfe)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/reth/reth/target/debug/build/reth-mdbx-sys-aed84e34750f284d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/reth/.cargo/git/checkouts/reth-36d3ea1d1152b20c/80793cf/crates/storage/libmdbx-rs/mdbx-sys/libmdbx

  --- stderr
  /home/reth/.cargo/git/checkouts/reth-36d3ea1d1152b20c/80793cf/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h:184:10: fatal error: 'stdarg.h' file not found
  thread 'main' panicked at /home/reth/.cargo/git/checkouts/reth-36d3ea1d1152b20c/80793cf/crates/storage/libmdbx-rs/mdbx-sys/build.rs:110:10:
  Unable to generate bindings: ClangDiagnostic("/home/reth/.cargo/git/checkouts/reth-36d3ea1d1152b20c/80793cf/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h:184:10: fatal error: 'stdarg.h' file not found\n")
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
     1: core::panicking::panic_fmt
               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::generate_bindings
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

80793cfe173d6ab87a6239be7f8d99605590e15e

### What database version are you on?

Does not apply. My reth exex service does not compile.

### Which chain / network are you on?

Does not apply. My reth exex service does not compile.

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

cargo install --path . && cargo build --release && ./reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by shekhirin** [comment]
Please install the required dependencies https://reth.rs/installation/source.html#dependencies
