### ISSUE TITLE
debug_execution_witness bug

### ISSUE THREAD

**Issue by 0x00101010** [paradigmxyz/reth#10756]
### Describe the bug

rpc return: 

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32603,
        "message": "internal blocking task error"
    }
}
```

internal logs:

```
thread '<unnamed>' panicked at /app/crates/trie/trie/src/witness.rs:144:13:
assertion `left == right` failed
  left: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
 right: 0x76092902092f8dc9ad6d08d82029e3c2a36c8120687843a2e223fdd9665db4bf
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:365:5
   4: reth_trie::witness::TrieWitness<T,H>::compute
             at ./crates/trie/trie/src/witness.rs:144:13
   5: <reth_trie::witness::TrieWitness<reth_trie_db::trie_cursor::DatabaseTrieCursorFactory<TX>,reth_trie_db::hashed_cursor::DatabaseHashedCursorFactory<TX>> as reth_trie_db::witness::DatabaseTrieWitness<TX>>::overlay_witness
             at ./crates/trie/db/src/witness.rs:39:9
   6: <reth_provider::providers::state::historical::HistoricalStateProviderRef<TX> as reth_storage_api::trie::StateProofProvider>::witness
             at ./crates/storage/provider/src/providers/state/historical.rs:373:9
   7: <reth_provider::providers::state::historical::HistoricalStateProvider<TX> as reth_storage_api::trie::StateProofProvider>::witness
             at ./crates/storage/provider/src/providers/state/macros.rs:14:21
   8: reth_storage_api::trie::_::<impl reth_storage_api::trie::StateProofProvider for alloc::boxed::Box<T>>::witness
             at ./crates/storage/storage-api/src/trie.rs:58:1
   9: <reth_rpc_eth_types::cache::db::StateProviderTraitObjWrapper as reth_storage_api::trie::StateProofProvider>::witness
             at ./crates/rpc/rpc-eth-types/src/cache/db.rs:79:9
  10: reth_rpc::debug::DebugApi<Provider,Eth>::debug_execution_witness::{{closure}}::{{closure}}
             at ./crates/rpc/rpc/src/debug.rs:674:31
  11: reth_rpc_eth_api::helpers::call::Call::spawn_with_state_at_block::{{closure}}
             at ./crates/rpc/rpc-eth-api/src/helpers/call.rs:363:13
  12: reth_rpc_eth_api::helpers::blocking_task::SpawnBlocking::spawn_tracing::{{closure}}
             at ./crates/rpc/rpc-eth-api/src/helpers/blocking_task.rs:74:58
  13: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs:272:9
  14: std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  15: __rust_try
  16: std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  17: std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  18: reth_tasks::pool::BlockingTaskPool::spawn::{{closure}}
             at ./crates/tasks/src/pool.rs:93:35
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs:272:9
  20: std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  21: __rust_try
  22: std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  23: std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  24: rayon_core::unwind::halt_unwinding
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/unwind.rs:17:5
  25: rayon_core::registry::Registry::catch_unwind
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:367:27
  26: rayon_core::spawn::spawn_job::{{closure}}
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/spawn/mod.rs:97:13
  27: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:169:9
  28: rayon_core::job::JobRef::execute
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:64:9
  29: rayon_core::registry::WorkerThread::execute
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:860:9
  30: rayon_core::registry::WorkerThread::wait_until_cold
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:794:21
  31: rayon_core::registry::WorkerThread::wait_until
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:769:13
  32: rayon_core::registry::WorkerThread::wait_until_out_of_work
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:818:9
  33: rayon_core::registry::main_loop
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:923:5
  34: rayon_core::registry::ThreadBuilder::run
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:53:18
  35: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /root/.asdf/installs/rust/1.81.0/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:98:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps to reproduce

Currently the existing debug_execution_witness API does not work (even with `main` branch). Steps to reproduce (see error message at the end):
1. 
2. git clone https://github.com/ethpandaops/ethereum-package.git
3. go to `ethereum-package`
4. update `network_params.yml` with latest reth container
5. install kurtosis if needed
6. `kurtosis clean --all && kurtosis run --enclave l1-reth-testnet ./ --args-file network_params.yaml --verbosity DETAILED`
7. call rpc (docker ps and find out)
```
curl --location 'http://localhost:<port>' \
--header 'Content-Type: application/json' \
--data '{
	"jsonrpc":"2.0",
	"method":"debug_executionWitness",
	"params":[
        "0x1",
        true
	],
	"id":1
}'
```

### Platform(s)

Linux (ARM)

### What version/commit are you on?

1.81

### What database version are you on?

just main branch version

### Which chain / network are you on?

dev

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by emhane** [comment]
I don't know if we can fix this, docker container will be single threaded and not support having a `rayon::ThreadPool` next to the tokio executor. cc @Rjected

**Comment by Rjected** [comment]
> I don't know if we can fix this, docker container will be single threaded and not support having a `rayon::ThreadPool` next to the tokio executor. cc @Rjected

I think the blocking task error is just noting that the task panicked, due to the failing assert:
```
thread '<unnamed>' panicked at /app/crates/trie/trie/src/witness.rs:144:13:
assertion `left == right` failed
  left: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
 right: 0x76092902092f8dc9ad6d08d82029e3c2a36c8120687843a2e223fdd9665db4bf
stack backtrace:
```

So probably unrelated to the type of threadpool used

**Comment by mattsse** [comment]
optimistically marking this as resolved because this code changed a lot, if this happens again, please open a new issue
