### ISSUE TITLE
Archive node crash with setting --engine.experimental

### ISSUE THREAD

**Issue by MrFrogoz** [paradigmxyz/reth#11570]
### Describe the bug

My node got stuck with this error and when I reboot it doesn't start, do I have to initialize from snapshot or is there a recover command? It happened several times can you fix it?

### Steps to reproduce
```
ExecStart=/root/build/op-node \
    --network=base-mainnet \
    --l1=........ \
    --l2=http://localhost:8551 \
    --rpc.addr=0.0.0.0 \
    --rpc.port=60004 \
    --l2.jwt-secret=/root/build/jwt.hex \
    --l1.trustrpc \
    --l1.rpckind=basic \
    --l1.beacon=........ \
    --syncmode=execution-layer 

ExecStart=/root/build/op-reth node \
    --chain=base \
    --datadir=/db/reth/base \
    --authrpc.addr=0.0.0.0 \
    --authrpc.port=8551 \
    --authrpc.jwtsecret=/root/build/jwt.hex \
    --http.port=50004 \
    --http.addr=0.0.0.0 \
    --http.corsdomain=* \
    --http \
    --ws \
    --http.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots \
    --rollup.sequencer-http=https://mainnet-sequencer.base.org \
    --rpc-max-connections=1000000 \
    --rpc-max-tracing-requests=1000000 \
    --engine.experimental
```

### Node logs

```text
Oct 08 11:49:20  op-reth[14973]: 2024-10-08T11:49:20.316634Z  INFO Block added to canonical chain number=20798838 hash=0x5aaff1999d815fe9347a109c503d9e63304156779d9699d85f9da5332a13b628 peers=1 txs=103 gas=17.69 Mgas gas_throughput=39.54 Mgas/second full=12.3% base_fee=0.00gwei blobs=0 excess_blobs=0 elapsed=447.331131ms
Oct 08 11:49:20  op-reth[14973]: 2024-10-08T11:49:20.564517Z  INFO Block added to canonical chain number=20798839 hash=0x095c1f06341cea90dbb8fc2b0a672d90669c617032c5e93b24abbbe9e7dd0707 peers=1 txs=103 gas=15.96 Mgas gas_throughput=64.42 Mgas/second full=11.1% base_fee=0.00gwei blobs=0 excess_blobs=0 elapsed=247.771232ms
Oct 08 11:49:20  op-reth[14973]: 2024-10-08T11:49:20.891515Z  INFO Block added to canonical chain number=20798840 hash=0x6fabbf0b736d17ffa0de0a453f2e82433e1b5f9c116bee96c94059f4a249baba peers=1 txs=135 gas=23.29 Mgas gas_throughput=71.26 Mgas/second full=16.2% base_fee=0.00gwei blobs=0 excess_blobs=0 elapsed=326.855463ms
Oct 08 11:49:20  op-reth[14973]: thread 'reth-rayon-2' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-trie-0.6.0/src/hash_builder/mod.rs:116:9:
Oct 08 11:49:20  op-reth[14973]: add_leaf key Nibbles("05030e020a090203020406070d07010f09080f0108070f03010808010c0007000403020d00030a07030901030d0c04010f09090701030f0703060a0a0a060503") self.key Nibbles("060e010504000107010b060c000c0906000b07010a070002000d090f06000007070f060a0f0903010a080b0b0f0509000d0a000202030d0a0c0f07050c070a0f")
Oct 08 11:49:20  op-reth[14973]: stack backtrace:
Oct 08 11:49:20  op-reth[14973]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 08 11:49:20  op-reth[14973]: Rayon: detected unexpected panic; aborting
Oct 08 11:49:21 systemd[1]: op-reth.service: Main process exited, code=killed, status=6/ABRT
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

latest

### What database version are you on?

latest

### Which chain / network are you on?

base

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by rkrasiuk** [comment]
@MrFrogoz can you share more logs please? also, could you specify the exact commit/hash version you are running?

**Comment by MrFrogoz** [comment]
There are no other logs, all repetitive of the incoming blocks and then this one of the error.

```
./op-reth --version
reth-optimism-cli Version: 1.0.8
Commit SHA: d72e438c06e040e213b5decf5f29543c86cbad0f
Build Timestamp: 2024-10-03T17:20:22.234976208Z
Build Features: asm_keccak,optimism
Build Profile: maxperf

./op-node --version
op-node version v1.9.1-4797ddb7-1724853807
```

**Comment by ymonye** [comment]
Try upgrading to op-node v1.9.3 & see if the error persists, despite being an op-reth error. Which version of Rust are you on?

**Comment by BowTiedDevil** [comment]
My node recently crashed with a similar error and is now in an inconsistent state.

Here's the output from journalctl leading up to the crash.

```
Oct 08 11:52:38 dev base_reth[677354]: 2024-10-08T18:52:38.930903Z  INFO Canonical chain committed number=20812105 hash=0x279b0913a8d0d5a671b9f71ccd831b9218084e85395aa239982abfd0ea175bf1 elapsed=172.774µs
Oct 08 11:52:40 dev base_reth[677354]: 2024-10-08T18:52:40.529999Z  INFO Block added to canonical chain number=20812106 hash=0x948dc76b936d0da9ea0bca96ec32d03026f5dee105b77801d0b6469049295894 peers=85 txs=161 gas=22.62 Mgas gas_throughput=122.14 Mgas/second full=15.7% base_fee=0.01gwei blobs=0 excess_blobs=0 elapsed=185.196906ms
Oct 08 11:52:40 dev base_reth[677354]: 2024-10-08T18:52:40.530752Z  INFO Canonical chain committed number=20812106 hash=0x948dc76b936d0da9ea0bca96ec32d03026f5dee105b77801d0b6469049295894 elapsed=206.635µs
Oct 08 11:52:42 dev base_reth[677354]: 2024-10-08T18:52:42.358190Z  INFO Block added to canonical chain number=20812107 hash=0x4129943b8aa69eff288678c58758fa19636d598b2a663d33aa468e943de669e6 peers=85 txs=130 gas=19.96 Mgas gas_throughput=78.16 Mgas/second full=13.9% base_fee=0.01gwei blobs=0 excess_blobs=0 elapsed=255.335376ms
Oct 08 11:52:42 dev base_reth[677354]: 2024-10-08T18:52:42.358848Z  INFO Canonical chain committed number=20812107 hash=0x4129943b8aa69eff288678c58758fa19636d598b2a663d33aa468e943de669e6 elapsed=193.995µs
Oct 08 11:52:44 dev base_reth[677354]: 2024-10-08T18:52:44.244615Z  INFO Block added to canonical chain number=20812108 hash=0x924bec621f90c205238f1adab221c1518e6343d601141ebb2222183eb226d5c8 peers=85 txs=91 gas=21.11 Mgas gas_throughput=117.02 Mgas/second full=14.7% base_fee=0.01gwei blobs=0 excess_blobs=0 elapsed=180.40321ms
Oct 08 11:52:44 dev base_reth[677354]: 2024-10-08T18:52:44.245187Z  INFO Canonical chain committed number=20812108 hash=0x924bec621f90c205238f1adab221c1518e6343d601141ebb2222183eb226d5c8 elapsed=163.374µs
Oct 08 11:52:46 dev base_reth[677354]: 2024-10-08T18:52:46.262244Z  INFO Block added to canonical chain number=20812109 hash=0x9f37d8d612e8ae4ddf259460b958791eb26361e20b04a5ea288e8617d9773eb8 peers=85 txs=134 gas=21.98 Mgas gas_throughput=152.15 Mgas/second full=15.3% base_fee=0.01gwei blobs=0 excess_blobs=0 elapsed=144.448199ms
Oct 08 11:52:46 dev base_reth[677354]: 2024-10-08T18:52:46.262822Z  INFO Canonical chain committed number=20812109 hash=0x9f37d8d612e8ae4ddf259460b958791eb26361e20b04a5ea288e8617d9773eb8 elapsed=202.054µs
Oct 08 11:52:48 dev base_reth[677354]: 2024-10-08T18:52:48.354062Z  INFO Block added to canonical chain number=20812110 hash=0x429b04e7c3c0f0a31f86d603ea25af6e97d44685e11ace8820f83c9ad57716ad peers=85 txs=144 gas=26.02 Mgas gas_throughput=137.96 Mgas/second full=18.1% base_fee=0.01gwei blobs=0 excess_blobs=0 elapsed=188.623689ms
Oct 08 11:52:48 dev base_reth[677354]: 2024-10-08T18:52:48.356379Z  INFO Canonical chain committed number=20812110 hash=0x429b04e7c3c0f0a31f86d603ea25af6e97d44685e11ace8820f83c9ad57716ad elapsed=370.04µs
Oct 08 11:52:50 dev base_reth[677354]: 2024-10-08T18:52:50.337285Z  INFO Block added to canonical chain number=20812111 hash=0x2a59d3cb38a311371cc7afb1a5a09c87698a8a5e4fd0e84f65e9193615d82258 peers=85 txs=102 gas=20.01 Mgas gas_throughput=78.44 Mgas/second full=13.9% base_fee=0.01gwei blobs=0 excess_blobs=0 elapsed=255.146151ms
Oct 08 11:52:50 dev base_reth[677354]: 2024-10-08T18:52:50.338009Z  INFO Canonical chain committed number=20812111 hash=0x2a59d3cb38a311371cc7afb1a5a09c87698a8a5e4fd0e84f65e9193615d82258 elapsed=256.036µs
Oct 08 11:52:51 dev base_reth[677354]: thread 'reth-rayon-5' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-trie-0.6.0/src/hash_builder/mod.rs:116:9:
Oct 08 11:52:51 dev base_reth[677354]: add_leaf key Nibbles("05030e020a090203020406070d07010f09080f0108070f03010808010c0007000403020d00030a07030901030d0c04010f09090701030f0703060a0a0a060503") self.key Nibbles("060e010504000107010b060c000c0906000b07010a070002000d090f06000007070f060a0f0903010a080b0b0f0509000d0a000202030d0a0c0f07050c070a0f")
Oct 08 11:52:51 dev base_reth[677354]: stack backtrace:
Oct 08 11:52:51 dev base_reth[677354]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 08 11:52:51 dev base_reth[677354]: Rayon: detected unexpected panic; aborting
Oct 08 11:54:09 dev systemd-coredump[1596352]: Process 677356 (op-reth) of user 1000 dumped core.
                                               
                                               Stack trace of thread 34:
                                               #0  0x00007f3df6774a24 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x174a24)
                                               #1  0x00007f3df69f1a0f n/a (/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 + 0xea0f)
                                               ELF object binary architecture: AMD x86-64
Oct 08 11:54:12 dev podman[1598985]: 2024-10-08 11:54:12.598653391 -0700 PDT m=+0.019997336 container died
```

I'm using op-node version v1.9.4-dev.0-c6478013-1727887423, op-reth version 1.0.8 with this pruning config:
```
[prune]
block_interval = 5

[prune.segments]
sender_recovery = "full"
account_history = { distance = 10064 }
storage_history = { distance = 10064 }
```
and the service is managed through podman / systemd with these options:
```
[Unit]
Description=Reth Execution Client (Base Mainnet)

[Container]
Image=ghcr.io/paradigmxyz/op-reth:latest
Pull=newer
ContainerName=base_reth
Pod=reth.pod
AutoUpdate=registry
StopTimeout=300
Volume=reth_jwt:/jwt:z,ro
Volume=base_reth_ipc:/ipc:z
Volume=/mnt/data/reth_base:/data:Z
Exec=node \
        --engine.experimental \
        --disable-discv4-discovery \
        --enable-discv5-discovery \
        --chain base \
        --datadir /data \
        --instance 3 \
        --discovery.v5.addr 0.0.0.0 \
        --discovery.v5.addr.ipv6 :: \
        --rollup.sequencer-http https://mainnet-sequencer.base.org \
        --rollup.disable-tx-pool-gossip \
        --http \
        --http.corsdomain * \
        --http.api all \
        --ws \
        --ws.origins * \
        --ws.api all \
        --ipcpath /ipc/reth.ipc \
        --authrpc.jwtsecret /jwt/jwt.hex

[Service]
Restart=on-failure
TimeoutSec=300

[Install]
WantedBy=default.target
```

**Comment by BowTiedDevil** [comment]
@MrFrogoz I recovered the node by stopping it, unwinding the database by 10,000 blocks, and restarting.

I use Podman instead of Docker, but the command I used is similar enough that you should be able to adapt it for your node:

```
podman run -v /mnt/data/reth_base/:/data/:Z ghcr.io/paradigmxyz/op-reth:latest stage unwind --chain base --datadir /data num-blocks 10000
```

**Comment by mattsse** [comment]
@MrFrogoz was this resolved?

**Comment by MrFrogoz** [comment]
yes but this problem still remains https://github.com/paradigmxyz/reth/issues/11306
