### ISSUE TITLE
Kurtosis failing within hours

### ISSUE THREAD

**Issue by w-woloszyn** [paradigmxyz/reth#11746]
### Describe the bug

After some time, about a day, Kurtosis instance goes down and refuses to come back up.

Logs from beacon:
```at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:542) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getStateForCommitteeDuties(ValidatorApiHandler.java:788) ~[teku-beacon-validator-24.10.1.jar:24.10.1]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getSyncCommitteeDuties(ValidatorApiHandler.java:279) ~[teku-beacon-validator-24.10.1.jar:24.10.1]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:80) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:125) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:116) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot calculate sync committee duties for epoch 7423 because it is not within the current or next sync committee periods
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$getStateForCommitteeDuties$32(ValidatorApiHandler.java:798) ~[teku-beacon-validator-24.10.1.jar:24.10.1]
... 15 more
2024-10-14 13:26:58.139 ERROR - Failed to request validator duties for epoch 7943. Retrying after delay.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Attestation duties were requested 1125 epochs ahead, only 1 epoch in future is supported.
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:620) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:31) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:424) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$22(SafeFuture.java:327) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:80) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:72) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Attestation duties were requested 1125 epochs ahead, only 1 epoch in future is supported.
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getAttestationDuties(ValidatorApiHandler.java:249) ~[teku-beacon-validator-24.10.1.jar:24.10.1]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:80) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:125) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:116) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
... 3 more
2024-10-14 13:26:58.139 ERROR - Failed to request validator duties for epoch 7942. Retrying after delay.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Proposer duties were requested for a future epoch (current: 6818, requested: 7942).
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:620) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:31) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:424) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$22(SafeFuture.java:327) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:80) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:72) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-24.10.1.jar:24.10.1]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Proposer duties were requested for a future epoch (current: 6818, requested: 7942).
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getProposerDuties(ValidatorApiHandler.java:295) ~[teku-beacon-validator-24.10.1.jar:24.10.1]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:80) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:125) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:116) ~[teku-infrastructure-events-24.10.1.jar:24.10.1]
```

Logs from Reth:

```2024-10-14T12:49:28.261650Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:49:53.260949Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:50:18.261079Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:50:40.033272Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=18602.75431842s
2024-10-14T12:50:43.260785Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:51:08.260704Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:51:33.261198Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:51:58.261005Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:52:23.261243Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:52:48.261088Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:53:13.261481Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:53:38.260869Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:54:03.261305Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:54:28.260834Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:54:53.265103Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:55:18.261203Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:55:40.033273Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=18902.754319849s
2024-10-14T12:55:43.261466Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:56:08.265118Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:56:33.261557Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:56:58.261111Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:57:23.260718Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:57:48.261394Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:58:13.261323Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:58:38.261426Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:59:03.261084Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:59:28.260678Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T12:59:53.260744Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:00:18.260978Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:00:40.032748Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=19202.753792336s
2024-10-14T13:00:43.261302Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:01:08.261085Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:01:33.264106Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:01:58.261010Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:02:23.261259Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:02:48.261128Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:03:13.261642Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:03:38.261343Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:04:03.261576Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:04:28.261176Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:04:53.260924Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:05:18.263112Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:05:40.033035Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=19502.754079489s
2024-10-14T13:05:43.261457Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:06:08.261037Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:06:33.261633Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:06:58.261025Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:07:23.260976Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:07:48.260679Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:08:13.261200Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:08:38.261350Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:09:03.261216Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:09:28.261416Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:09:53.263505Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:10:18.261451Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:10:40.033516Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=19802.754561238s
2024-10-14T13:10:43.261381Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:11:08.262089Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:11:33.260652Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:11:58.261084Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:12:23.261542Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:12:48.260771Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:13:13.260766Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:13:38.261224Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:14:03.260789Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:14:28.261361Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:14:53.261472Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:15:18.260657Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:15:40.036114Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=20102.757155778s
2024-10-14T13:15:43.260757Z  INFO Status connected_peers=1 latest_block=22536
2024-10-14T13:16:08.261083Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:16:33.260728Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:16:58.261379Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:17:23.260748Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:17:48.261295Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:18:13.261186Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:18:38.261493Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:19:03.260716Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:19:28.260822Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:19:53.260817Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:20:18.261208Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:20:40.034097Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=20402.755143219s
2024-10-14T13:20:43.261516Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:21:08.260746Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:21:33.261597Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:21:58.261397Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:22:23.261625Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:22:48.260797Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:23:13.260736Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:23:38.261369Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:24:03.260972Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:24:28.261226Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:24:53.261207Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:25:18.261193Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:25:40.033323Z  WARN Beacon client online, but no consensus updates received for a while. This may be because of a reth error, or an error in the beacon client! Please investigate reth and beacon client logs! period=20702.754368242s
2024-10-14T13:25:43.261362Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:26:08.260810Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:26:33.261551Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:26:58.260747Z  INFO Status connected_peers=0 latest_block=22536
2024-10-14T13:27:23.260867Z  INFO Status connected_peers=0 latest_block=22536
```

### Steps to reproduce

1. Start Reth with Kurtosis `kurtosis run github.com/ethpandaops/ethereum-package --args-file network_params.yaml --image-download always`. The network_params.yaml can be left default.
3. Wait for about a day
4. Kurtosis should die eventually

### Platform(s)

Linux (x86)

### What version/commit are you on?

commit f51ac78d5a5b59da378a15fbeeb74969720faeb3

### What database version are you on?

Kurtosis default

### Which chain / network are you on?

Kurtosis default

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

Kurtosis default

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Rjected** [comment]
Hey, closing this because this looks like a teku error, given the CL error logs
