### ISSUE TITLE
Run test failed from source on macOS

### ISSUE THREAD

**Issue by GrapeBaBa** [paradigmxyz/reth#1219]
### Describe the bug

Some tests failed when run `cargo test --all --all-features`.

### Steps to reproduce

```sh
  cd reth
  cargo test --all --all-features
```

```sh
failures:

---- implementation::mdbx::tests::db_cursor_insert stdout ----
thread 'implementation::mdbx::tests::db_cursor_insert' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- implementation::mdbx::tests::db_cursor_walk_range stdout ----
thread 'implementation::mdbx::tests::db_cursor_walk_range' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_append_failure stdout ----
thread 'implementation::mdbx::tests::db_cursor_append_failure' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_insert_wherever_cursor_is stdout ----
thread 'implementation::mdbx::tests::db_cursor_insert_wherever_cursor_is' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_append stdout ----
thread 'implementation::mdbx::tests::db_cursor_append' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_creation stdout ----
thread 'implementation::mdbx::tests::db_creation' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_dupsort_append stdout ----
thread 'implementation::mdbx::tests::db_cursor_dupsort_append' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_sharded_key stdout ----
thread 'implementation::mdbx::tests::db_sharded_key' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_walk stdout ----
thread 'implementation::mdbx::tests::db_cursor_walk' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_closure_put_get stdout ----
thread 'implementation::mdbx::tests::db_closure_put_get' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_seek_exact_or_previous_key stdout ----
thread 'implementation::mdbx::tests::db_cursor_seek_exact_or_previous_key' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_iterate_over_all_dup_values stdout ----
thread 'implementation::mdbx::tests::db_iterate_over_all_dup_values' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_walker stdout ----
thread 'implementation::mdbx::tests::db_walker' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_manual_put_get stdout ----
thread 'implementation::mdbx::tests::db_manual_put_get' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_reverse_walker stdout ----
thread 'implementation::mdbx::tests::db_reverse_walker' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_dup_sort stdout ----
thread 'implementation::mdbx::tests::db_dup_sort' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::dup_value_with_same_subkey stdout ----
thread 'implementation::mdbx::tests::dup_value_with_same_subkey' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46


failures:
    implementation::mdbx::tests::db_closure_put_get
    implementation::mdbx::tests::db_creation
    implementation::mdbx::tests::db_cursor_append
    implementation::mdbx::tests::db_cursor_append_failure
    implementation::mdbx::tests::db_cursor_dupsort_append
    implementation::mdbx::tests::db_cursor_insert
    implementation::mdbx::tests::db_cursor_insert_wherever_cursor_is
    implementation::mdbx::tests::db_cursor_seek_exact_or_previous_key
    implementation::mdbx::tests::db_cursor_walk
    implementation::mdbx::tests::db_cursor_walk_range
    implementation::mdbx::tests::db_dup_sort
    implementation::mdbx::tests::db_iterate_over_all_dup_values
    implementation::mdbx::tests::db_manual_put_get
    implementation::mdbx::tests::db_reverse_walker
    implementation::mdbx::tests::db_sharded_key
    implementation::mdbx::tests::db_walker
    implementation::mdbx::tests::dup_value_with_same_subkey

test result: FAILED. 30 passed; 17 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.21s

```

### Node logs

```text
failures:

---- implementation::mdbx::tests::db_cursor_insert stdout ----
thread 'implementation::mdbx::tests::db_cursor_insert' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- implementation::mdbx::tests::db_cursor_walk_range stdout ----
thread 'implementation::mdbx::tests::db_cursor_walk_range' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_append_failure stdout ----
thread 'implementation::mdbx::tests::db_cursor_append_failure' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_insert_wherever_cursor_is stdout ----
thread 'implementation::mdbx::tests::db_cursor_insert_wherever_cursor_is' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_append stdout ----
thread 'implementation::mdbx::tests::db_cursor_append' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_creation stdout ----
thread 'implementation::mdbx::tests::db_creation' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_dupsort_append stdout ----
thread 'implementation::mdbx::tests::db_cursor_dupsort_append' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_sharded_key stdout ----
thread 'implementation::mdbx::tests::db_sharded_key' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_walk stdout ----
thread 'implementation::mdbx::tests::db_cursor_walk' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_closure_put_get stdout ----
thread 'implementation::mdbx::tests::db_closure_put_get' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_cursor_seek_exact_or_previous_key stdout ----
thread 'implementation::mdbx::tests::db_cursor_seek_exact_or_previous_key' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_iterate_over_all_dup_values stdout ----
thread 'implementation::mdbx::tests::db_iterate_over_all_dup_values' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_walker stdout ----
thread 'implementation::mdbx::tests::db_walker' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_manual_put_get stdout ----
thread 'implementation::mdbx::tests::db_manual_put_get' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_reverse_walker stdout ----
thread 'implementation::mdbx::tests::db_reverse_walker' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::db_dup_sort stdout ----
thread 'implementation::mdbx::tests::db_dup_sort' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46

---- implementation::mdbx::tests::dup_value_with_same_subkey stdout ----
thread 'implementation::mdbx::tests::dup_value_with_same_subkey' panicked at 'Not able to create the mdbx file.: DatabaseLocation(15)', crates/storage/db/src/implementation/mdbx/mod.rs:139:46


failures:
    implementation::mdbx::tests::db_closure_put_get
    implementation::mdbx::tests::db_creation
    implementation::mdbx::tests::db_cursor_append
    implementation::mdbx::tests::db_cursor_append_failure
    implementation::mdbx::tests::db_cursor_dupsort_append
    implementation::mdbx::tests::db_cursor_insert
    implementation::mdbx::tests::db_cursor_insert_wherever_cursor_is
    implementation::mdbx::tests::db_cursor_seek_exact_or_previous_key
    implementation::mdbx::tests::db_cursor_walk
    implementation::mdbx::tests::db_cursor_walk_range
    implementation::mdbx::tests::db_dup_sort
    implementation::mdbx::tests::db_iterate_over_all_dup_values
    implementation::mdbx::tests::db_manual_put_get
    implementation::mdbx::tests::db_reverse_walker
    implementation::mdbx::tests::db_sharded_key
    implementation::mdbx::tests::db_walker
    implementation::mdbx::tests::dup_value_with_same_subkey

test result: FAILED. 30 passed; 17 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.21s
```

### Platform(s)

Mac (Intel)

### What version/commit are you on?

commit at 314ea0883b1062375ad86577be1fccc39233739d

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by GrapeBaBa** [comment]
```sh
(base) kaichen@Kais-MacBook-Pro reth % uname -a
Darwin Kais-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

(base) kaichen@Kais-MacBook-Pro reth % /usr/bin/clang++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

(base) kaichen@Kais-MacBook-Pro reth % /usr/bin/clang --version 
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

**Comment by GrapeBaBa** [comment]
@gakonst What other env information need I provide?

**Comment by onbjerg** [comment]
Does this also happen if you use `nextest`? See here: https://nexte.st/book/installation.html and run `cargo nextest run`

**Comment by GrapeBaBa** [comment]
> Does this also happen if you use `nextest`? See here: https://nexte.st/book/installation.html and run `cargo nextest run`

```sh
cargo nextest run
    Finished test [unoptimized + debuginfo] target(s) in 2.01s
    Starting 3 tests across 2 binaries
        PASS [   0.248s] reth test_eth_chain::models::test::blockchain_test_deserialize
        PASS [   0.164s] reth test_eth_chain::models::test::header_deserialize
        PASS [   0.086s] reth test_eth_chain::models::test::transaction_deserialize
------------
     Summary [   0.252s] 3 tests run: 3 passed, 0 skipped

```

**Comment by gakonst** [comment]
What was that error code again? `Not able to create the mdbx file.: DatabaseLocation(15)',`

I am still unable to repro.

**Comment by GrapeBaBa** [comment]
https://github.com/paradigmxyz/reth/blob/afb6671a0f8c681e1fc3b3d13d6a33f30c954dd2/crates/storage/libmdbx-rs/src/environment.rs#L414-L472

exception throw at environment open

**Comment by GrapeBaBa** [comment]
Check the error code in MDBX, 15 is indeed an INCOMPATIBLE error.
![image](https://user-images.githubusercontent.com/3657859/218256783-bcf052ce-ea91-40e2-9952-94586316ba75.png)

**Comment by gakonst** [comment]
https://erthink.github.io/libmdbx/group__c__settings.html

> If the database is already exist, opened with [MDBX_EXCLUSIVE](https://erthink.github.io/libmdbx/group__c__opening.html#gga9138119a904355d245777c4119534061aa516c74e6fed22c9812bb909c8c459ed) or not used by any other process, and parameters specified by [mdbx_env_set_geometry()](https://erthink.github.io/libmdbx/group__c__settings.html#ga79065e4f3c5fb2ad37a52b59224d583e) are incompatible (i.e. for instance, different page size) then [mdbx_env_open()](https://erthink.github.io/libmdbx/group__c__opening.html#gabb7dd3b10dd31639ba252df545e11768) will return [MDBX_INCOMPATIBLE](https://erthink.github.io/libmdbx/group__c__err.html#ggab5ba1469eef28a2e09ed243b608b11ceaf8d7b0a9b9c20a0eab9850268f616666) error.

Hmmm can you try cloning fresh and retrying? Not sure honestly.

**Comment by GrapeBaBa** [comment]
> https://erthink.github.io/libmdbx/group__c__settings.html
> 
> > If the database is already exist, opened with [MDBX_EXCLUSIVE](https://erthink.github.io/libmdbx/group__c__opening.html#gga9138119a904355d245777c4119534061aa516c74e6fed22c9812bb909c8c459ed) or not used by any other process, and parameters specified by [mdbx_env_set_geometry()](https://erthink.github.io/libmdbx/group__c__settings.html#ga79065e4f3c5fb2ad37a52b59224d583e) are incompatible (i.e. for instance, different page size) then [mdbx_env_open()](https://erthink.github.io/libmdbx/group__c__opening.html#gabb7dd3b10dd31639ba252df545e11768) will return [MDBX_INCOMPATIBLE](https://erthink.github.io/libmdbx/group__c__err.html#ggab5ba1469eef28a2e09ed243b608b11ceaf8d7b0a9b9c20a0eab9850268f616666) error.
> 
> Hmmm can you try cloning fresh and retrying? Not sure honestly.

what do you mean `cloning fresh`?

**Comment by mattsse** [comment]
has this since been resolved @GrapeBaBa ?

**Comment by gakonst** [comment]
given @GrapeBaBa has been opening PRs recently I assume yes, so closing optimistically
