### ISSUE TITLE
Op-reth compiler issue

### ISSUE THREAD

**Issue by malik672** [paradigmxyz/reth#12399]
### Describe the bug

When running make lint on the codebase, clippy encounters an Internal Compiler Error (ICE) while evaluating trait bounds in the reth-optimism-node crate. The error occurs specifically while checking Send implementations for nested tokio channel types.

### Error Details

The compiler panics while evaluating:
`tokio::sync::oneshot::Sender<tokio::sync::broadcast::Receiver<reth_payload_primitives::events::Events<engine::OptimismEngineTypes>>>: core::marker::Send
`
Full error stack:
'rustc' panicked at compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:23:54:
called `Option::unwrap()` on a `None` value

saw this once, reran it again and encountered the same issue. reverted all my changes in the codebase to it's original form and still encountered the issue, skipped it then now I've encountered it again

### Steps to reproduce

1. Clone reth repository
2. Run make lint
3. Observe clippy panic during optimization node checks

### Node logs

```text
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:23:54:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x111397b64 - std::backtrace::Backtrace::create::h38331fefa18b97b9
   1:        0x10f287904 - <alloc[240efccdb53fc12f]::boxed::Box<rustc_driver_impl[818fc7bc80f3f00c]::install_ice_hook::{closure#0}> as core[65ac7e790faddaa0]::ops::function::Fn<(&dyn for<'a, 'b> core[65ac7e790faddaa0]::ops::function::Fn<(&'a std[4265e78211a8ccfd]::panic::PanicHookInfo<'b>,), Output = ()> + core[65ac7e790faddaa0]::marker::Sync + core[65ac7e790faddaa0]::marker::Send, &std[4265e78211a8ccfd]::panic::PanicHookInfo)>>::call
   2:        0x1113b22f8 - std::panicking::rust_panic_with_hook::h6965295fc494c3ec
   3:        0x1113b1f4c - std::panicking::begin_panic_handler::{{closure}}::h328421691e0665d1
   4:        0x1113afb58 - std::sys::backtrace::__rust_end_short_backtrace::hdc3dc458da0ff80b
   5:        0x1113b1c38 - _rust_begin_unwind
   6:        0x113a335a4 - core::panicking::panic_fmt::h2b8c16abe5bf2077
   7:        0x113a33614 - core::panicking::panic::h9691dd3a3fabccde
   8:        0x113a3353c - core::option::unwrap_failed::h30453648661b6fac
   9:        0x10fea5ca4 - <rustc_metadata[3173d5b13d4082cb]::rmeta::decoder::cstore_impl::provide_cstore_hooks::{closure#0} as core[65ac7e790faddaa0]::ops::function::FnOnce<(rustc_middle[99ab855d0efbbcf5]::query::plumbing::TyCtxtAt, rustc_span[5f3f762fc4fb81dd]::def_id::DefPathHash, rustc_span[5f3f762fc4fb81dd]::def_id::StableCrateId)>>::call_once
  10:        0x10ff36434 - <rustc_middle[99ab855d0efbbcf5]::ty::context::TyCtxt>::def_path_hash_to_def_id
  11:        0x1108dce20 - <rustc_query_impl[fee6ea5a1897d0d4]::plumbing::query_callback<rustc_query_impl[fee6ea5a1897d0d4]::query_impl::type_of::QueryType>::{closure#0} as core[65ac7e790faddaa0]::ops::function::FnOnce<(rustc_middle[99ab855d0efbbcf5]::ty::context::TyCtxt, rustc_query_system[30ffef2ab3376262]::dep_graph::dep_node::DepNode)>>::call_once
  12:        0x110ac9b94 - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  13:        0x110ac9b3c - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  14:        0x110ac9b3c - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  15:        0x110ac9b3c - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  16:        0x110ac9b3c - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  17:        0x110ac9b3c - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  18:        0x110ac9b3c - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  19:        0x110ac9b3c - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  20:        0x110ac9924 - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  21:        0x110845204 - rustc_query_system[30ffef2ab3376262]::query::plumbing::try_execute_query::<rustc_query_impl[fee6ea5a1897d0d4]::DynamicConfig<rustc_query_system[30ffef2ab3376262]::query::caches::DefaultCache<rustc_type_ir[61f747155366298b]::canonical::CanonicalQueryInput<rustc_middle[99ab855d0efbbcf5]::ty::context::TyCtxt, rustc_middle[99ab855d0efbbcf5]::ty::ParamEnvAnd<rustc_middle[99ab855d0efbbcf5]::ty::predicate::Predicate>>, rustc_middle[99ab855d0efbbcf5]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt, true>
  22:        0x110b350d8 - rustc_query_impl[fee6ea5a1897d0d4]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  23:        0x110f98db8 - <rustc_infer[a45fd6ed5071b1d9]::infer::InferCtxt as rustc_trait_selection[9476bdbaeaf5dec5]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  24:        0x110f9919c - <rustc_infer[a45fd6ed5071b1d9]::infer::InferCtxt as rustc_trait_selection[9476bdbaeaf5dec5]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  25:        0x1111450ac - <rustc_trait_selection[9476bdbaeaf5dec5]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  26:        0x111144674 - <rustc_trait_selection[9476bdbaeaf5dec5]::traits::fulfill::FulfillProcessor as rustc_data_structures[b45a364606ce9507]::obligation_forest::ObligationProcessor>::process_obligation
  27:        0x1111228ec - <rustc_data_structures[b45a364606ce9507]::obligation_forest::ObligationForest<rustc_trait_selection[9476bdbaeaf5dec5]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[9476bdbaeaf5dec5]::traits::fulfill::FulfillProcessor>
  28:        0x111140098 - <rustc_trait_selection[9476bdbaeaf5dec5]::traits::fulfill::FulfillmentContext<rustc_trait_selection[9476bdbaeaf5dec5]::traits::FulfillmentError> as rustc_infer[a45fd6ed5071b1d9]::traits::engine::TraitEngine<rustc_trait_selection[9476bdbaeaf5dec5]::traits::FulfillmentError>>::select_where_possible
  29:        0x11113b774 - <rustc_trait_selection[9476bdbaeaf5dec5]::traits::fulfill::FulfillmentContext<rustc_trait_selection[9476bdbaeaf5dec5]::traits::FulfillmentError> as rustc_infer[a45fd6ed5071b1d9]::traits::engine::TraitEngine<rustc_trait_selection[9476bdbaeaf5dec5]::traits::FulfillmentError>>::select_all_or_error
  30:        0x10f632404 - rustc_hir_analysis[8566fa3e014fc211]::check::compare_impl_item::check_type_bounds
  31:        0x10f624490 - rustc_hir_analysis[8566fa3e014fc211]::check::check::check_impl_items_against_trait
  32:        0x10f61d44c - rustc_hir_analysis[8566fa3e014fc211]::check::check::check_item_type
  33:        0x10f5d2610 - rustc_hir_analysis[8566fa3e014fc211]::check::wfcheck::check_well_formed
  34:        0x11090a0ec - rustc_query_impl[fee6ea5a1897d0d4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fee6ea5a1897d0d4]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[99ab855d0efbbcf5]::query::erase::Erased<[u8; 1usize]>>
  35:        0x110ae2718 - <rustc_query_impl[fee6ea5a1897d0d4]::query_impl::check_well_formed::dynamic_query::{closure#2} as core[65ac7e790faddaa0]::ops::function::FnOnce<(rustc_middle[99ab855d0efbbcf5]::ty::context::TyCtxt, rustc_span[5f3f762fc4fb81dd]::def_id::LocalDefId)>>::call_once
  36:        0x1108a8f0c - rustc_query_system[30ffef2ab3376262]::query::plumbing::try_execute_query::<rustc_query_impl[fee6ea5a1897d0d4]::DynamicConfig<rustc_query_system[30ffef2ab3376262]::query::caches::VecCache<rustc_span[5f3f762fc4fb81dd]::def_id::LocalDefId, rustc_middle[99ab855d0efbbcf5]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt, true>
  37:        0x1108030cc - rustc_query_system[30ffef2ab3376262]::query::plumbing::force_query::<rustc_query_impl[fee6ea5a1897d0d4]::DynamicConfig<rustc_query_system[30ffef2ab3376262]::query::caches::VecCache<rustc_span[5f3f762fc4fb81dd]::def_id::LocalDefId, rustc_middle[99ab855d0efbbcf5]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  38:        0x1108d06f0 - <rustc_query_impl[fee6ea5a1897d0d4]::plumbing::query_callback<rustc_query_impl[fee6ea5a1897d0d4]::query_impl::check_well_formed::QueryType>::{closure#0} as core[65ac7e790faddaa0]::ops::function::FnOnce<(rustc_middle[99ab855d0efbbcf5]::ty::context::TyCtxt, rustc_query_system[30ffef2ab3376262]::dep_graph::dep_node::DepNode)>>::call_once
  39:        0x110ac9b94 - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  40:        0x110ac9924 - <rustc_query_system[30ffef2ab3376262]::dep_graph::graph::DepGraphData<rustc_middle[99ab855d0efbbcf5]::dep_graph::DepsType>>::try_mark_green::<rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  41:        0x110806058 - rustc_query_system[30ffef2ab3376262]::query::plumbing::ensure_must_run::<rustc_query_impl[fee6ea5a1897d0d4]::DynamicConfig<rustc_query_system[30ffef2ab3376262]::query::caches::DefaultCache<rustc_span[5f3f762fc4fb81dd]::def_id::LocalModDefId, rustc_middle[99ab855d0efbbcf5]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt>
  42:        0x110b11120 - rustc_query_impl[fee6ea5a1897d0d4]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  43:        0x10f52fe3c - <rustc_data_structures[b45a364606ce9507]::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures[b45a364606ce9507]::sync::parallel::enabled::par_for_each_in<&rustc_hir[f8311b8fe71f794b]::hir_id::OwnerId, &[rustc_hir[f8311b8fe71f794b]::hir_id::OwnerId], <rustc_middle[99ab855d0efbbcf5]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[8566fa3e014fc211]::check_crate::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>
  44:        0x10f59566c - <rustc_session[ac6f15ba6106228a]::session::Session>::time::<(), rustc_hir_analysis[8566fa3e014fc211]::check_crate::{closure#0}>
  45:        0x10f52c080 - rustc_hir_analysis[8566fa3e014fc211]::check_crate
  46:        0x10fb83aa8 - rustc_interface[d3777d291916c9e7]::passes::analysis
  47:        0x11090dbf0 - rustc_query_impl[fee6ea5a1897d0d4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[fee6ea5a1897d0d4]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[99ab855d0efbbcf5]::query::erase::Erased<[u8; 1usize]>>
  48:        0x110a60f5c - <rustc_query_impl[fee6ea5a1897d0d4]::query_impl::analysis::dynamic_query::{closure#2} as core[65ac7e790faddaa0]::ops::function::FnOnce<(rustc_middle[99ab855d0efbbcf5]::ty::context::TyCtxt, ())>>::call_once
  49:        0x11082a270 - rustc_query_system[30ffef2ab3376262]::query::plumbing::try_execute_query::<rustc_query_impl[fee6ea5a1897d0d4]::DynamicConfig<rustc_query_system[30ffef2ab3376262]::query::caches::SingleCache<rustc_middle[99ab855d0efbbcf5]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[fee6ea5a1897d0d4]::plumbing::QueryCtxt, true>
  50:        0x110aff908 - rustc_query_impl[fee6ea5a1897d0d4]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  51:        0x10f2703b0 - <rustc_interface[d3777d291916c9e7]::queries::QueryResult<&rustc_middle[99ab855d0efbbcf5]::ty::context::GlobalCtxt>>::enter::<core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>, rustc_driver_impl[818fc7bc80f3f00c]::run_compiler::{closure#0}::{closure#1}::{closure#5}>
  52:        0x10f241fd0 - <rustc_interface[d3777d291916c9e7]::interface::Compiler>::enter::<rustc_driver_impl[818fc7bc80f3f00c]::run_compiler::{closure#0}::{closure#1}, core[65ac7e790faddaa0]::result::Result<core[65ac7e790faddaa0]::option::Option<rustc_interface[d3777d291916c9e7]::queries::Linker>, rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>
  53:        0x10f2b8e5c - rustc_span[5f3f762fc4fb81dd]::create_session_globals_then::<core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>, rustc_interface[d3777d291916c9e7]::util::run_in_thread_with_globals<rustc_interface[d3777d291916c9e7]::util::run_in_thread_pool_with_globals<rustc_interface[d3777d291916c9e7]::interface::run_compiler<core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>, rustc_driver_impl[818fc7bc80f3f00c]::run_compiler::{closure#0}>::{closure#1}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>::{closure#0}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  54:        0x10f2720f8 - std[4265e78211a8ccfd]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d3777d291916c9e7]::util::run_in_thread_with_globals<rustc_interface[d3777d291916c9e7]::util::run_in_thread_pool_with_globals<rustc_interface[d3777d291916c9e7]::interface::run_compiler<core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>, rustc_driver_impl[818fc7bc80f3f00c]::run_compiler::{closure#0}>::{closure#1}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>::{closure#0}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>
  55:        0x10f26813c - <<std[4265e78211a8ccfd]::thread::Builder>::spawn_unchecked_<rustc_interface[d3777d291916c9e7]::util::run_in_thread_with_globals<rustc_interface[d3777d291916c9e7]::util::run_in_thread_pool_with_globals<rustc_interface[d3777d291916c9e7]::interface::run_compiler<core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>, rustc_driver_impl[818fc7bc80f3f00c]::run_compiler::{closure#0}>::{closure#1}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>::{closure#0}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[65ac7e790faddaa0]::result::Result<(), rustc_span[5f3f762fc4fb81dd]::ErrorGuaranteed>>::{closure#1} as core[65ac7e790faddaa0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  56:        0x1113bc724 - std::sys::pal::unix::thread::Thread::new::thread_start::h6b98e9ae71cc0684
  57:        0x19228df94 - __pthread_joiner_wake


rustc version: 1.84.0-nightly (da935398d 2024-10-19)
platform: aarch64-apple-darwin

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `tokio::sync::oneshot::Sender<tokio::sync::broadcast::Receiver<reth_payload_primitives::events::Events<engine::OptimismEngineTypes>>>: core::marker::Send`
#1 [check_well_formed] checking that `node::<impl at crates/optimism/node/src/node.rs:94:1: 98:7>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

https://github.com/paradigmxyz/reth/pull/12228
from here

### What database version are you on?

skip

### Which chain / network are you on?

skip

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

skip

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by malik672** [comment]
this is where i believe the error is from: 
```

#[derive(Debug, Default, Clone, serde::Deserialize, serde::Serialize)]
#[non_exhaustive]
pub struct OptimismEngineTypes<T: PayloadTypes = OptimismPayloadTypes> {
    _marker: std::marker::PhantomData<T>,
}

impl<T: PayloadTypes> EngineTypes for OptimismEngineTypes<T>
where
    T::BuiltPayload: TryInto<ExecutionPayloadV1>
        + TryInto<ExecutionPayloadEnvelopeV2>
        + TryInto<OpExecutionPayloadEnvelopeV3>
        + TryInto<OpExecutionPayloadEnvelopeV4>,
```

**Comment by klkvr** [comment]
probably related

did you try running `cargo clean` and retrying again? I've hit this a couple of times and it is usually getting fixed after cleaning

**Comment by malik672** [comment]
> probably related [rust-lang/rust#130283](https://github.com/rust-lang/rust/issues/130283)
> 
> did you try running `cargo clean` and retrying again? I've hit this a couple of times and it is usually getting fixed after cleaning

Yep, worked for me, closing it then.
