### ISSUE TITLE
Merkle trie root mismatch at #18193583

### ISSUE THREAD

**Issue by d347h-eth** [paradigmxyz/reth#4735]
### Describe the bug

Been running (synced) archive node and just got this crash. Uptime was just a few hours, but overall operated normally for week+ before.
Seems like the node can't recover by itself and is stuck at 18193582 (reth-after-restart.log).
~Unwound 100 blocks by hand and normal operation resumed.~
See https://twitter.com/gakonst/status/1705317461007208610

### Steps to reproduce

Everything running on defaults through provided docker compose.

### Node logs

```text
https://gist.github.com/d347h-eth/d0cfd1942da5c7977f916dccb65cd625
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.8 Commit SHA: 0f14ec4 Build Timestamp: 2023-08-28T18:03:09.906989731Z Build Features: default,jemalloc Build Profile: maxperf

### What database version are you on?

Current database version: 1
Local database version: 1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mcseemk** [comment]
Same issue, same block. I'm running alpha 8 full node. Logs from reth:

> 2023-09-22T19:53:37.033711Z  INFO try_insert_validated_block{block=(18193583, 0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001)}: blockchain_tree: return=Ok(Valid)
2023-09-22T19:53:37.033759Z  INFO reth::node::events: Block added to canonical chain number=18193583 hash=0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001
2023-09-22T19:53:37.125329Z  INFO make_canonical{block_hash=0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001}: blockchain_tree: Committing new canonical chain: [(18193583, 0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001)]
2023-09-22T19:53:37.393777Z ERROR consensus::engine: Encountered fatal error err=CanonicalCommit { inner: "Merkle trie root mismatch at #18193583 (0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001). Got: 0xe95f6e570066479d0b8dbb22140d6927d777f4d8e755d2fdc5658e01f9fb3ead. Expected: 0x386622e8941c98423ee7e3ecca7206b4848f2dad083a36e7aab06d9334927775" }

Logs from CL Lodestar. Those are timestamped in UTC+7 timezone, by the way:

> Sep-23 02:53:29.124[]                 ^[[32minfo^[[39m: Synced - slot: 7382365 - head: 0x00f3…f2db - exec-block: valid(18193582 0xac5a…) - finalized: 0xf4db…7975:230696 - peers: 94
Sep-23 02:53:37.431[execution]        ^[[33mwarn^[[39m: Execution client is syncing oldState=SYNCED, newState=SYNCING
Sep-23 02:53:37.432[chain]           ^[[31merror^[[39m: Error pushing notifyForkchoiceUpdate() headBlockHash=0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001, finalizedBlockHash=0xfbdb0abe55947528f95063aa19d230acd01fe10a85613951ed2aac491006c257 JSON RPC error: Transaction error on commit: "Merkle trie root mismatch at #18193583 (0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001). Got: 0xe95f6e570066479d0b8dbb22140d6927d777f4d8e755d2fdc5658e01f9fb3ead. Expected: 0x386622e8941c98423ee7e3ecca7206b4848f2dad083a36e7aab06d9334927775", engine_forkchoiceUpdatedV2
Error: JSON RPC error: Transaction error on commit: "Merkle trie root mismatch at #18193583 (0x6d8bb254949ded71703e23f467422c626ee2885a3026450b06bfb9f8ab0d6001). Got: 0xe95f6e570066479d0b8dbb22140d6927d777f4d8e755d2fdc5658e01f9fb3ead. Expected: 0x386622e8941c98423ee7e3ecca7206b4848f2dad083a36e7aab06d9334927775", engine_forkchoiceUpdatedV2
	at parseRpcResponse (file:///tank/mcs/src/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:266:11)
	at JsonRpcHttpClient.fetchWithRetries (file:///tank/mcs/src/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:134:12) 
	at processTicksAndRejections (node:internal/process/task_queues:95:5)
	at ExecutionEngineHttp.fetchWithRetries (file:///tank/mcs/src/lodestar/packages/beacon-node/src/execution/engine/http.ts:133:19)
	at JobItemQueue.runJob (file:///tank/mcs/src/lodestar/packages/beacon-node/src/util/queue/itemQueue.ts:101:22)

**Comment by d347h-eth** [comment]
@mcseemk Current recommendations are these: https://twitter.com/gakonst/status/1705350867535417427 - seems to help a few people to recover.
I'm still trying to re-sync on the latest `main`.

**Comment by d347h-eth** [comment]
I'm back in sync after 1k blocks unwind and running the latest `main`! :tada:

**Comment by jasalper** [comment]
Same here, adding for added logs:

Running commit 

```commit 1eee5ee80a7148a8ab8c83a2a5c498f07e1db48c (HEAD)
Author: Alexey Shekhirin <a.shekhirin@gmail.com>
Date:   Wed Aug 23 18:45:53 2023 +0100

    feat(pruner, primitives): move prune batch sizes to `ChainSpec` (#4318)

    Co-authored-by: joshieDo <ranriver@protonmail.com>```

Version:
`reth 0.1.0-alpha.7 (VERGEN_IDEMPOTENT_OUTPUT) starting`

Last 100 lines of the logs are here:
https://gist.github.com/jasalper/9bb511d3f61b01e1f6a2c6780b1740eb

I saved 10k lines, but the earlier ones look pretty reasonable. lmk if you want more.

**Comment by d347h-eth** [comment]
> `reth 0.1.0-alpha.7 (VERGEN_IDEMPOTENT_OUTPUT) starting`

I guess worth to mention here, that it's expected for you to be updated to the latest alpha release at all times. Now we know that only [v0.1.0-alpha.9](https://github.com/paradigmxyz/reth/tree/v0.1.0-alpha.9) (just released) is the only stable/supported one.
