### ISSUE TITLE
eth_getBlockReceipts should be able to support blockHash params

### ISSUE THREAD

**Issue by kaliubuntu0206** [paradigmxyz/reth#5084]
### Describe the bug

It only supports block numbers instead.

The latest rpc specification for eth_getBlockReceipts defines to support either blockHash or block number for params

https://github.com/ethereum/execution-apis/pull/438/files#diff-116730f9786fa2f36b3c96b968f82419b2ebf694054f04dd0d3224372bf5579eR89

Here is what I got when I try to query blockHash

```
Error while fetching block receipts
Error: could not coalesce error (error={ "code": -32602, "data": "number too large to fit in target type", "message": "Invalid params" }, payload={ "id": 3, "jsonrpc": "2.0", "method": "eth_getBlockReceipts", "params": [ "0x1e22a0d24d014cb8c560444bce0f3f5d2c12cd32dc85306907bc0b33feb89ff9" ] }, code=UNKNOWN_ERROR, version=6.8.0)
    at makeError (/home/ubuntu/test/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at JsonRpcProvider.getRpcError (/home/ubuntu/test/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:653:41)
    at /home/ubuntu/test/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:268:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: {
    code: -32602,
    message: 'Invalid params',
    data: 'number too large to fit in target type'
  },
  payload: {
    method: 'eth_getBlockReceipts',
    params: [
      '0x1e22a0d24d014cb8c560444bce0f3f5d2c12cd32dc85306907bc0b33feb89ff9'
    ],
    id: 3,
    jsonrpc: '2.0'
  },
  shortMessage: 'could not coalesce error'
}
```

### Steps to reproduce

1. Query 'eth_getBlockReceipts' with blockHash params
2. Fails since the node could not recognize it

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by kaliubuntu0206** [comment]
@mattsse That was fast, thank you
