### ISSUE TITLE
Sync Error between Lighthouse and RETH

### ISSUE THREAD

**Issue by eliseygusev** [paradigmxyz/reth#5220]
### Describe the bug

I am running RETH as execution node and lighthouse as consensus node. Periodically RETH node panics and shuts down.

I haven't saved the reth logs the first time but today it showed:
Failed to canonicalize the head hash error=Execution(CanonicalCommit { inner: "Database write operation \"CursorAppendDup\" for key \"[0, 0, 0, 0, 1, 25, 144, 44, 0, 0, 0, 0, 0, 0, 0, 173, 192, 76, 86, 191, 48, 172, 157, 60, 10, 175, 20, 220]\" in table \"StorageChangeSet\" ended with error code: -30418" })

thread 'tokio-runtime-worker' panicked at /home/ubuntu/reth/crates/blockchain-tree/src/blockchain_tree.rs:189:36:
Chain id is valid

Issue resolves if I manually restart the reth node

### Steps to reproduce

1. Latitude sh server with RAID (merging, non-duplicating)
2. Run latest RETH built from sources
3. Run lighthouse v4.5.0
4. After sync it sometimes appears

### Node logs

```text
2023-10-29T01:23:12.337213Z  INFO reth::node::events: Forkchoice updated head_block_hash=0xe6b48f338a28546de6dc49d44dcb0530302d3c0e4f965aa9e200b0d2b78d6d50 safe_block_hash=0xe2115425e997db0cf79bea48586a07bf19f89facfc01c87e2d5a229ec9551474 finalized_block_hash=0x3ea9b167120ab7479e83707dea1c7639c40d1f7123afb579d583be2ed7baa1ec status=Valid
2023-10-29T01:23:12.924316Z  INFO reth::node::events: Block added to canonical chain number=18452527 hash=0xc4d05b46db8306416c21818bdff2af7b4b31d8fe82ccb4c7bf0debd77d65bb3c
2023-10-29T01:23:12.924391Z  INFO blockchain_tree: Unwinding canonical chain blocks: 18452526..=18452526
2023-10-29T01:23:13.160180Z  WARN consensus::engine: Failed to canonicalize the head hash error=Execution(CanonicalCommit { inner: "Database write operation \"CursorAppendDup\" for key \"[0, 0, 0, 0, 1, 25, 144, 44, 0, 0, 0, 0, 0, 0, 0, 173, 192, 76, 86, 191, 48, 172, 157, 60, 10, 175, 20, 220]\" in table \"StorageChangeSet\" ended with error code: -30418" }) state=ForkchoiceState { head_block_hash: 0x30f6a6212845b703f243667e483a8a128fa5b29f7f6fc86a0cb0cb6440ecb015, safe_block_hash: 0xe2115425e997db0cf79bea48586a07bf19f89facfc01c87e2d5a229ec9551474, finalized_block_hash: 0x3ea9b167120ab7479e83707dea1c7639c40d1f7123afb579d583be2ed7baa1ec }
2023-10-29T01:23:13.160221Z  INFO reth::node::events: Forkchoice updated head_block_hash=0x30f6a6212845b703f243667e483a8a128fa5b29f7f6fc86a0cb0cb6440ecb015 safe_block_hash=0xe2115425e997db0cf79bea48586a07bf19f89facfc01c87e2d5a229ec9551474 finalized_block_hash=0x3ea9b167120ab7479e83707dea1c7639c40d1f7123afb579d583be2ed7baa1ec status=Syncing
thread 'tokio-runtime-worker' panicked at /home/ubuntu/reth/crates/blockchain-tree/src/blockchain_tree.rs:189:36:
Chain id is valid
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
2023-10-29T01:23:13.170991Z ERROR reth_tasks: Critical task consensus engine panicked: Chain id is valid
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.10 Commit SHA: d3de32a9

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Full via --full flag

### If you've built Reth from source, provide the full command you used

cargo build --release

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
@rkrasiuk @rakita reorged block https://etherscan.io/block/18452526/f

maybe missed some cleanup on unwind?
