### ISSUE TITLE
hardhat client cannot send transaction

### ISSUE THREAD

**Issue by vbar** [paradigmxyz/reth#5555]
### Describe the bug

I'm trying to run the custom chain example at https://blog.superchain.network/inside-reth-the-journey-of-a-tranaction-through-ethereum/ , except with hardhat client - which can connect, but cannot send a transaction.

### Steps to reproduce

server (as in https://blog.superchain.network/inside-reth-the-journey-of-a-tranaction-through-ethereum/ ), with the same `chain.json`:
```
eth node -d --chain chain.json --datadir ml_reth --auto-mine --http
```

hardhat client:
```
$ npx hardhat console --network local
Welcome to Node.js v18.18.0.
Type ".help" for more information.
> let signer = (await hre.ethers.getSigners())[0]
undefined
> await signer.sendTransaction({
...   to: "0x944fDcD1c868E3cC566C78023CcB38A32cDA836E",
...   value: "1"
... })
Uncaught ProviderError: unknown block number
    at HttpProvider.request (/home/vb/client-report/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HardhatEthersProvider.estimateGas (/home/vb/client-report/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:237:27)
    at async /home/vb/client-report/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:235:35
    at async Promise.all (index 0)
    at async HardhatEthersSigner._sendUncheckedTransaction (/home/vb/client-report/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:256:7)
    at async HardhatEthersSigner.sendTransaction (/home/vb/client-report/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async REPL5:1:33
    at async node:repl:616:29
```

Meanwhile, the foundry `cast` client works:
```
$ cast send --from 0xd143C405751162d0F96bEE2eB5eb9C61882a736E --value 1 --legacy --private-key 0xcece4f25ac74deb1468965160c7185e07dff413f23fcadb611b05ca37ab0a52e 0x944fDcD1c868E3cC566C78023CcB38A32cDA836E

blockHash               0xf199786a55474e2032fcee1c67344395e325b53380d6742e987261005d5da2f6
blockNumber             1
contractAddress         
cumulativeGasUsed       21000
effectiveGasPrice       2000000000
gasUsed                 21000
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root                    
status                  1
transactionHash         0x759686ad683dc0f21c61cf3796821f7d94f6190107455ac823334cc6440bf0e1
transactionIndex        0
type                    0
```

### Node logs

```text
failure server log (with RUST_LOG="rpc::eth=trace"):

2023-11-24T07:05:49.235894Z TRACE rpc::eth: clear stale filters
2023-11-24T07:06:56.835216Z TRACE rpc::eth: Serving eth_chainId
2023-11-24T07:07:09.596501Z TRACE rpc::eth: Serving eth_blockNumber
2023-11-24T07:07:09.602982Z TRACE rpc::eth: Serving eth_estimateGas request=CallRequest { from: Some(0xd143c405751162d0f96bee2eb5eb9c61882a736e), to: Some(0x944fdcd1c868e3cc566c78023ccb38a32cda836e), gas_price: None, max_fee_per_gas: None, max_priority_fee_per_gas: None, gas: None, value: Some(0x0000000000000000000000000000000000000000000000000000000000000001_U256), input: CallInput { input: None, data: None }, nonce: None, chain_id: None, access_list: None, max_fee_per_blob_gas: None, blob_versioned_hashes: None, transaction_type: None } block_number=Some(Number(Pending))
```

success server log:
```
2023-11-24T07:03:03.078644Z TRACE rpc::eth: clear stale filters
2023-11-24T07:04:58.706514Z TRACE rpc::eth: Serving eth_chainId
2023-11-24T07:04:58.707042Z TRACE rpc::eth: Serving eth_getTransactionCount address=0xd143c405751162d0f96bee2eb5eb9c61882a736e block_number=Some(Number(Latest))
2023-11-24T07:04:58.707646Z TRACE rpc::eth: Serving eth_gasPrice
2023-11-24T07:04:58.708095Z TRACE rpc::eth: Serving eth_estimateGas request=CallRequest { from: Some(0xd143c405751162d0f96bee2eb5eb9c61882a736e), to: Some(0x944fdcd1c868e3cc566c78023ccb38a32cda836e), gas_price: Some(0x0000000000000000000000000000000000000000000000000000000077359400_U256), max_fee_per_gas: None, max_priority_fee_per_gas: None, gas: None, value: Some(0x0000000000000000000000000000000000000000000000000000000000000001_U256), input: CallInput { input: None, data: None }, nonce: Some(0x0_U64), chain_id: None, access_list: None, max_fee_per_blob_gas: None, blob_versioned_hashes: None, transaction_type: Some(0x0_U8) } block_number=None
2023-11-24T07:04:58.708836Z TRACE rpc::eth: Serving eth_sendRawTransaction tx=Bytes(0xf86580847735940082520894944fdcd1c868e3cc566c78023ccb38a32cda836e0180826095a02451b19046f73a8486bd8e4a9c73f7b4bb995d9cb5b3759c2e63af4f218fb9eca03e0baeca9019149ab67e98df8e04e7fd682de2d6ae7f5aca4ad8a1f3592f1e6e)
2023-11-24T07:04:58.709346Z TRACE rpc::eth: Serving eth_getTransactionReceipt hash=0x759686ad683dc0f21c61cf3796821f7d94f6190107455ac823334cc6440bf0e1
2023-11-24T07:04:58.810365Z TRACE rpc::eth: Serving eth_getTransactionByHash hash=0x759686ad683dc0f21c61cf3796821f7d94f6190107455ac823334cc6440bf0e1
2023-11-24T07:04:58.811363Z TRACE rpc::eth: Serving eth_getTransactionReceipt hash=0x759686ad683dc0f21c61cf3796821f7d94f6190107455ac823334cc6440bf0e1
```
```


### Platform(s)

Linux (x86)

### What version/commit are you on?

337fb311eebdc2e31e7ed257d4cc655ec7c557f0

### What database version are you on?

ml_reth directory removed before running the server

```
$ reth db version
Current database version: 1
Local database is uninitialized
```

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

cargo install --locked --path bin/reth --bin reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
send_transaction is effectively useless, because there are no signers configured by default

we could however add support for them in --dev mode

**Comment by vbar** [comment]
> send_transaction is effectively useless, because there are no signers configured by default

That `chain.json` has a couple of funded addresses, and the account of the first is sending the transaction. The communication fails sooner anyway, at `eth_estimateGas` - apparently hardhat (unlike cast) uses its second argument, which reth doesn't handle...

**Comment by mattsse** [comment]
hmm, I see.
looks like it doesn't find the latest block number.

could you please add the entire request as json object?

**Comment by vbar** [comment]
> could you please add the entire request as json object?

sure - wireshark says
```
{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"value":"0x1","from":"0xd143c405751162d0f96bee2eb5eb9c61882a736e","to":"0x944fdcd1c868e3cc566c78023ccb38a32cda836e"},"pending"],"id":3}
```

**Comment by eigmax** [comment]
Is this fixed?  I have the same issue.
