### ISSUE TITLE
Crash on start, at least on a syncing database

### ISSUE THREAD

**Issue by 0xarbitrary** [paradigmxyz/reth#7263]
### Describe the bug

Since upgrading to beta.3, reth crashes on start, except when it's on a non-existing database. I haven't been able to check on a synced database because it always gets stuck at some point in the sync and I tried restarting it (I don't know if this is due to the same issue or a different one).

This happened first when upgrading to beta.3 from beta.2, which hadn't finished syncing. Then it happened 2 more times after I tried syncing from a fresh state and it had gotten stuck.

The shown errors are as following:

```
2024-03-21T06:01:15.583002Z  INFO Opening database path="/root/.local/share/reth/mainnet/db"
2024-03-21T06:01:15.605883Z  INFO Configuration loaded path="/root/.local/share/reth/mainnet/reth.toml"
2024-03-21T06:01:15.607744Z  INFO Database opened
2024-03-21T06:01:15.607755Z  INFO Starting metrics endpoint addr=0.0.0.0:9001
thread 'main' panicked at /project/crates/primitives/src/integer_list.rs:51:18:
IntegerList must be pre-sorted and non-empty: NonSortedIntegers { valid_until: 1 }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: reth_primitives::integer_list::IntegerList::new_pre_sorted
   4: reth_provider::providers::database::provider::DatabaseProvider<TX>::append_history_index
   5: reth_node_core::init::init_genesis
   6: reth_node_builder::builder::NodeBuilder<DB,reth_node_builder::builder::ComponentsState<Types,Components,reth_node_builder::components::traits::FullNodeComponentsAdapter<reth_node_builder::node::FullNodeTypesAdapter<Types,DB,reth_provider::providers::BlockchainProvider<DB,reth_blockchain_tree::shareable::ShareableBlockchainTree<DB,reth_revm::factory::EvmProcessorFactory<<Types as reth_node_builder::node::NodeTypes>::Evm>>>>,<Components as reth_node_builder::components::traits::NodeComponentsBuilder<reth_node_builder::node::FullNodeTypesAdapter<Types,DB,reth_provider::providers::BlockchainProvider<DB,reth_blockchain_tree::shareable::ShareableBlockchainTree<DB,reth_revm::factory::EvmProcessorFactory<<Types as reth_node_builder::node::NodeTypes>::Evm>>>>>>::Pool>>>::launch::{{closure}}
   7: reth_node_core::cli::runner::run_to_completion_or_panic::{{closure}}
   8: reth::cli::Cli<Ext>::run
   9: reth::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps to reproduce

1. Start syncing
2. Restart the container at some point in the syncing process.

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.3
Commit SHA: 56d688b
Build Timestamp: 2024-03-18T13:08:51.400134562Z
Build Features: jemalloc
Build Profile: maxperf

I'm using the ghcr.io/paradigmxyz/reth:v0.2.0-beta.3 docker image.

### What database version are you on?

Current database version: 2
Local database version: 2

### What type of node are you running?

Full via --full flag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by 0xqd** [comment]
Can you run on previous version of reth ( a version after this reth Version: 0.2.0-beta.3 ) now?

**Comment by 0xarbitrary** [comment]
Same error appears if I try to run beta.2 on the database created by beta.3

**Comment by 0xqd** [comment]
can you post the log here?

**Comment by 0xarbitrary** [comment]
Sure

```
2024-03-21T09:30:12.512676Z  INFO Opening database path="/root/.local/share/reth/mainnet/db"
2024-03-21T09:30:12.519447Z  INFO Configuration loaded path="/root/.local/share/reth/mainnet/reth.toml"
2024-03-21T09:30:12.519565Z  INFO Database opened
2024-03-21T09:30:12.519577Z  INFO Starting metrics endpoint addr=0.0.0.0:9001
thread 'main' panicked at /project/crates/primitives/src/integer_list.rs:51:18:
IntegerList must be pre-sorted and non-empty: NonSortedIntegers { valid_until: 1 }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: reth_primitives::integer_list::IntegerList::new_pre_sorted
   4: reth_provider::providers::database::provider::DatabaseProvider<TX>::append_history_index
   5: reth_node_core::init::init_genesis
   6: reth_node_builder::builder::NodeBuilder<DB,reth_node_builder::builder::ComponentsState<Types,Components,reth_node_builder::components::traits::FullNodeComponentsAdapter<reth_node_builder::node::FullNodeTypesAdapter<Types,DB,reth_provider::providers::BlockchainProvider<DB,reth_blockchain_tree::shareable::ShareableBlockchainTree<DB,reth_revm::factory::EvmProcessorFactory<<Types as reth_node_builder::node::NodeTypes>::Evm>>>>,<Components as reth_node_builder::components::traits::NodeComponentsBuilder<reth_node_builder::node::FullNodeTypesAdapter<Types,DB,reth_provider::providers::BlockchainProvider<DB,reth_blockchain_tree::shareable::ShareableBlockchainTree<DB,reth_revm::factory::EvmProcessorFactory<<Types as reth_node_builder::node::NodeTypes>::Evm>>>>>>::Pool>>>::launch::{{closure}}
   7: reth_node_core::cli::runner::run_to_completion_or_panic::{{closure}}
   8: reth::cli::Cli<Ext>::run
   9: reth::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by 0xqd** [comment]
@0xarbitrary Your problem might be related to this one https://github.com/paradigmxyz/reth/issues/7154
And I'm curious how do you upgrade your node ( gracefully upgrade, or forced terminate the node )

**Comment by Rjected** [comment]
> @0xarbitrary Your problem might be related to this one #7154 And I'm curious how do you upgrade your node ( gracefully upgrade, or forced terminate the node )

It's probably not related to that IMO

**Comment by fubuloubu** [comment]
For me, the node seems to stall out around 6X% on Stage 2, and then when I go to restart it I keep running into this issue. This was after purging the DB, which I've done twice now and still have the same issue

**Comment by fubuloubu** [comment]
Okay, I see the pattern here now, it seems to stall out on an update here:
![20240403_160800.jpg](https://github.com/paradigmxyz/reth/assets/3859395/1951e9a4-41f4-461a-83a7-c540b97edcd2)

Then when I restart my node, I get the OP error

Confirmed on beta.5 now

**Comment by Rjected** [comment]
> Okay, I see the pattern here now, it seems to stall out on a "fork choice update" message here: ![20240403_160800.jpg](https://private-user-images.githubusercontent.com/3859395/319340048-1951e9a4-41f4-461a-83a7-c540b97edcd2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzcyMzgsIm5iZiI6MTcxMjE3NjkzOCwicGF0aCI6Ii8zODU5Mzk1LzMxOTM0MDA0OC0xOTUxZTlhNC00MWY0LTQ2MWEtODNhNy1jNTQwYjk3ZWRjZDIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMjA0MjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk4MDkyN2JhMDUwYzYwYjE4ZTdmYWFjZGI4NzM1ZjhkOWNlYWEzZDFmZTk5Yzk5YTZjYTczYjlkODg2YzA3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CKwCVqN8veSzxUL2oXAsN-wea8I-O4g06_vmPOFJtaQ) (No logs occur showing the fault, the process simply shuts down with no failure indication)
> 
> Then when I restart my node, I get the OP error
> 
> Confirmed on beta.5 now
> 
> Also, unlike OP I am not restarting the container at any point, it just stalls and shuts itself off here

The shutdown without a trace is interesting, could you check for OOMs in dmesg?

**Comment by fgimenez** [comment]
@0xarbitrary, can you please share the list of files under `/root/.local/share/reth/mainnet/static_files` after the crash?
