### ISSUE TITLE
ExEx manager crashes on unwind

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#8737]
```console
2024-06-11T07:17:11.864409Z  INFO Unwinding{stage=Execution}: Starting unwind from=1711616 to=1711613 bad_block=Some(1711616)
thread 'tokio-runtime-worker' panicked at crates/exex/exex/src/manager.rs:290:85:
Chain should have at least one block
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-06-11T07:17:13.651002Z  INFO Unwinding{stage=Execution}: Stage unwound stage=Execution unwind_to=1711613 progress=1711613 done=true
2024-06-11T07:17:13.651585Z ERROR shutting down due to error
thread 'tokio-runtime-worker' panicked at /Users/shekhirin/Projects/reth/crates/node/builder/src/launch/exex.rs:74:34:
ExEx EVM finished. ExEx's should run indefinitely
2024-06-11T07:17:13.651631Z ERROR exex{id="EVM"}: Critical task `exex` panicked: `ExEx EVM finished. ExEx's should run indefinitely`
```

**Comment by shekhirin** [comment]
The issue is here https://github.com/paradigmxyz/reth/blob/55317eb004b67bb057aad3080643ee9bbc722182/crates/stages/stages/src/stages/execution.rs#L398

`provider.get_take_block_range` looks up the data only in MDBX, but we usually have it in static files, so we try to create a chain with no blocks.
