### ISSUE TITLE
make pr failed of lockfile

### ISSUE THREAD

**Issue by jsvisa** [paradigmxyz/reth#9381]
### Describe the bug

run `make test` failed of:

```bash
test lockfile::tests::test_drop_lock ... FAILED
test implementation::mdbx::tests::db_iterate_over_all_dup_values ... ok
test implementation::mdbx::tests::db_manual_put_get ... ok
test implementation::mdbx::tests::db_reverse_walker ... ok
test implementation::mdbx::tests::db_walker ... ok
test tables::codecs::fuzz::BlockNumberAddress::fuzz_fuzz::entry ... ok
test implementation::mdbx::tests::db_sharded_key ... ok
test implementation::mdbx::tests::dup_value_with_same_subkey ... ok
test tables::codecs::fuzz::IntegerList::fuzz_fuzz::entry ... ok
test tables::tests::parse_table_from_str ... ok
test implementation::mdbx::tests::db_walk_back ... ok
test utils::tests::is_database_empty_false_if_db_path_is_a_file ... ok
test version::tests::malformed_file ... ok
test version::tests::missing_file ... ok
test version::tests::version_mismatch ... ok
test tests::db_version ... ok
test tables::codecs::fuzz::IntegerList::fuzz_fuzz::auto_generate ... ok
test tables::codecs::fuzz::BlockNumberAddress::fuzz_fuzz::auto_generate ... ok
test lockfile::tests::test_lock ... FAILED
test tables::codecs::fuzz::IntegerList::test ... ok
test tables::codecs::fuzz::BlockNumberAddress::test ... ok
test implementation::mdbx::tx::tests::long_read_transaction_safety_enabled ... ok
test implementation::mdbx::tx::tests::long_read_transaction_safety_disabled ... ok
test tests::db_client_version ... ok

failures:

---- lockfile::tests::test_drop_lock stdout ----
thread 'lockfile::tests::test_drop_lock' panicked at crates/storage/db/src/lockfile.rs:186:9:
assertion failed: lock_file.exists()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- lockfile::tests::test_lock stdout ----
thread 'lockfile::tests::test_lock' panicked at crates/storage/db/src/lockfile.rs:171:9:
assertion `left == right` failed
  left: Err(Taken(1))
 right: Ok(StorageLock(StorageLockInner { file_path: "/var/folders/j2/hsd5xc515qq6x2chgx12s5ch0000gn/T/.tmpmcpYoq/lock" }))


failures:
    lockfile::tests::test_drop_lock
    lockfile::tests::test_lock

test result: FAILED. 39 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.55s

error: test failed, to rerun pass `-p reth-db --lib`

```

after some dig, it seems like the command `cargo test --lib --workspace  -p reth-db  -- lockfile::tests` failed to run, but `cargo test --lib -p reth-db  -- lockfile::tests` is success

### Steps to reproduce

`make pr`

### Platform(s)

Linux (x86), Mac (Apple Silicon)

### What version/commit are you on?

main

### What database version are you on?

2

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
@joshieDo I believe this happens because both tests are run in the same process in `cargo t`

we should run them in sequence with `serial_test` or some other sync mechanism
